import React from "react";

export type AnalyticsChartMetric = "total_tokens" | "llm_latency_ms" | "error_count";
export interface AnalyticsChartPoint { date: string; total_tokens: number; avg_latency_ms: number; error_count: number; }
interface AnalyticsTrendChartProps { data: AnalyticsChartPoint[]; metric: AnalyticsChartMetric; label: string; unit: string; }
function formatDay(date: string) { return new Intl.DateTimeFormat("ar-SA", { day: "numeric", month: "short" }).format(new Date(`${date}T00:00:00`)); }
export function AnalyticsTrendChart({ data, metric, label, unit }: AnalyticsTrendChartProps) {
  const values = data.map((point) => metric === "llm_latency_ms" ? point.avg_latency_ms : point[metric]);
  const maximum = Math.max(...values, 1);
  return <section aria-labelledby="analytics-trend-title" className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5 shadow-xl shadow-black/10"><div className="flex items-start justify-between gap-4"><div><h3 id="analytics-trend-title" className="text-sm font-bold text-zinc-100">????? {label}</h3><p className="mt-1 text-[11px] text-zinc-500">?????? ????? ?????? ???????</p></div><span className="rounded-lg border border-zinc-700 bg-zinc-950 px-2.5 py-1 text-[10px] font-semibold text-zinc-400">{unit}</span></div>{data.length === 0 ? <div className="flex h-64 items-center justify-center text-center text-xs text-zinc-500">?? ???? ?????? ????? ???? ????? ???????.</div> : <div className="mt-6" role="img" aria-label={`??? ????? ?????? ${label}`}><div className="flex h-56 items-end gap-2" dir="ltr">{data.map((point, index) => { const value = values[index]; const height = Math.max((value / maximum) * 100, value > 0 ? 4 : 0); return <div key={point.date} className="group flex min-w-0 flex-1 flex-col justify-end"><div className="relative flex h-48 items-end rounded-t-lg bg-zinc-950/60 px-1"><div className="w-full rounded-t-md bg-gradient-to-t from-indigo-600 to-indigo-400 transition-opacity group-hover:opacity-80" style={{ height: `${height}%` }} title={`${formatDay(point.date)}: ${value.toLocaleString("ar-SA")} ${unit}`} /></div><span className="mt-2 truncate text-center text-[9px] text-zinc-500" dir="rtl">{formatDay(point.date)}</span></div>; })}</div><div className="sr-only">{data.map((point, index) => <span key={point.date}>{formatDay(point.date)}: {values[index]} {unit}. </span>)}</div></div>}</section>;
}
